version: 2.1

aliases:

    - &docker_container
      docker:
        - image: circleci/golang:latest

jobs:
    job_00:
        <<: *docker_container
        description: echo stuff
        steps:
            - run:
                command: |
                    echo "echo-ing vars used"
                    echo "GITHUB_TOKEN: ${GITHUB_TOKEN}"
                    echo "CIRCLE_PROJECT_USERNAME: ${CIRCLE_PROJECT_USERNAME}"
                    echo "CIRCLE_PROJECT_REPONAME: ${CIRCLE_PROJECT_REPONAME}"
                    echo "CIRCLECI_TOKEN: ${CIRCLECI_TOKEN}"

    job_01:
        <<: *docker_container
        description: tags a branch
        steps:
            - run:
                name: setup github-release
                command: |
                    go get github.com/aktau/github-release
            - run:
                command: |
                    echo "getting release info"
                    github-release info \
                        -u ${CIRCLE_PROJECT_USERNAME} \
                        -r ${CIRCLE_PROJECT_REPONAME}

    job_02:
        <<: *docker_container
        description: get env vars
        steps:
            - run:
                command: |
                    curl https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/envvar?circle-token=${CIRCLECI_TOKEN}


workflows:
    version_branch:
        jobs:
            - job_00
            - job_01
            - job_02:
                filters:
                    branches:
                        only:
                            - master
