version: 2.1

orbs:

    jq: circleci/jq@1.9.1

aliases:

    - &docker_container
      docker:
        - image: circleci/golang:latest

    - &filter_master
      filters:
        branches:
            only:
                - master

jobs:
    echo_envvars:
        <<: *docker_container
        description: echo stuff
        steps:
            - run:
                command: |
                    echo "echo-ing vars used"
                    echo "CIRCLE_PROJECT_USERNAME: ${CIRCLE_PROJECT_USERNAME}"
                    echo "CIRCLE_PROJECT_REPONAME: ${CIRCLE_PROJECT_REPONAME}"
                    echo "ACME_CIRCLECI_API_TOKEN: ${ACME_CIRCLECI_API_TOKEN}"

    github_release_info:
        <<: *docker_container
        description: tags a branch
        steps:
            - run:
                name: setup github-release
                command: |
                    go get github.com/aktau/github-release
            - run:
                command: |
                    echo "getting release info"
                    github-release info \
                        -u ${CIRCLE_PROJECT_USERNAME} \
                        -r ${CIRCLE_PROJECT_REPONAME}

    list_envvars:
        <<: *docker_container
        description: get env vars
        steps:
            - run:
                command: |
                    curl https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/envvar?circle-token=${ACME_CIRCLECI_API_TOKEN}

    get_envvar_semver:
        <<: *docker_container
        description: get version envvar
        steps:
            - run:
                command: |
                    curl https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/envvar/SEMVER?circle-token=${ACME_CIRCLECI_API_TOKEN}

    delete_envvar_semver:
        <<: *docker_container
        description: delete version envvar
        steps:
            - run: 
                command: |
                    curl -X DELETE https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/envvar/SEMVER?circle-token=${ACME_CIRCLECI_API_TOKEN}
    
    get_github_version_DEPRICATED:
        <<: *docker_container
        description: call GH api to get latest version (GH DEPRICATED)
        steps:
            - run: 
                command: |
                    curl https://${GITHUB_TOKEN}@api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest
                
    
    get_github_version:
        <<: *docker_container
        description: call GH api to get latest version
        steps:
            - jq/install
            - run: 
                command: |
                    RESPONSE=$(curl -H "Authorization: ${GITHUB_TOKEN}" https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest)
                    TAG=$(echo $RESPONSE | jq -r '.tag_name')
                    MAJ_MIN=$(echo $TAG | sed "s/\.[^\.]*$//")
                    PATCH=$(echo $TAG | sed 's/.*\.//')
                    LATEST="$((PATCH + 1))"
                    NEW_SEMVER="$MAJ_MIN.$LATEST"
                    git tag $NEW_SEMVER && git push --tags

workflows:
    version_branch:
        jobs:
            #- echo_envvars:
            #    <<: *filter_master
            #- github_release_info:
            #    <<: *filter_master
            #    requires:
            #        - echo_envvars
            #- list_envvars:
            #    <<: *filter_master
            #    requires:
            #        - github_release_info
            #- get_envvar_semver:
            #    <<: *filter_master
            #    requires:
            #        - list_envvars
            #- delete_envvar_semver:
            #    <<: *filter_master
            #    requires:
            #        - get_envvar_semver
            - get_github_version:
                <<: *filter_master
            #    requires:
            #        - delete_envvar_semver
